In [1]:
import tensorflow as tf

In [2]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'),
 PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')]

### A tensor is an N-dimensional array of data


In [3]:
# Intialization of tensors
x = tf.constant(4)
x

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [4]:
x = tf.constant(4, shape=(1,1), dtype=tf.float32)
x

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [5]:
x = tf.constant(3, shape=(2,2))
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [3, 3]])>

In [6]:
x = tf.constant([[1,2,3], [4,5,6]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [7]:
x = tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [8]:
x = tf.zeros((2,3))
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [9]:
x = tf.eye(3) # identity matrix
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [10]:
#  uniform distribution refers to a type of probability distribution in which all outcomes are equally likely.
x = tf.random.uniform((3,3)) # uniform distribution
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.464746  , 0.31863356, 0.7599417 ],
       [0.8031126 , 0.5937457 , 0.13857853],
       [0.73870564, 0.68335795, 0.12667811]], dtype=float32)>

In [11]:
 # a probability distribution that is symmetric about the mean, showing that data near the mean are more frequent in occurrence than data far from the mean
x = tf.random.normal((3,3), mean=0, stddev=1) # standard normal distribution
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.4330219 ,  0.03838802,  0.71398   ],
       [ 0.2767514 , -0.9069785 , -0.71346205],
       [-1.1901907 , -1.3400944 ,  2.0849688 ]], dtype=float32)>

In [12]:
x = tf.range(10)
x

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [13]:
x = tf.range(start=1, limit=10, delta=2)
x

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

In [15]:
# tf.float (16,32,64), tf.int (8,16,32, 64)
# tf.bool
tf.cast(x, dtype=tf.float64)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 3., 5., 7., 9.])>

### Mathematical Operations

In [17]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

z = tf.add(x, y)
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [20]:
z = tf.subtract(y,x)
print(z)

tf.Tensor([8 6 4], shape=(3,), dtype=int32)


In [21]:
z = tf.divide(x, y)
print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [22]:
z = tf.multiply(x, y)
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [26]:
m = tf.tensordot(x, y, axes=1)
n = tf.reduce_sum(x*y, axis=0)
print(m)
print(n)

tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)


In [27]:
exp = x ** 2
print(exp)

tf.Tensor([1 4 9], shape=(3,), dtype=int32)


In [28]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))

z = tf.matmul(x, y) #  matrix mutiply
print(z)
z = x @ y # another way of matrix multiply

tf.Tensor(
[[ 1.088184   -0.69528586  0.65793777  0.20482138]
 [-4.3358684   1.2171452  -0.80880785  2.5973551 ]], shape=(2, 4), dtype=float32)


In [35]:
# Indexing
x = tf.constant([0, 1, 1, 2, 3, 1, 2,3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [36]:
indices = tf.constant([0, 3])
x_ind = tf.gather(x, indices)
print(x_ind) # get index number

tf.Tensor([0 2], shape=(2,), dtype=int32)


In [37]:
x = tf.constant([[1,2],
                [3,4],
                [5,6]
                ])

In [38]:
print(x[0,:])
print(x[0:2, :])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [41]:
# Reshaping
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [42]:
x = tf.reshape(x, (3,3))
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [43]:
x = tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
